### ISSUE TITLE
sound level value or raw value not changed on ios

### ISSUE THREAD

**Issue by roysG** [punarinta/react-native-sound-level#5]
When i test on android, everything works ok.
When i test on ios in real device this is the output i get:
Sound level info', { id: 1107, value: -120, rawValue: -120 }

**Comment by punarinta** [comment]
@roysG is that number the same on every run? It looks like a fixed non-zero (not -160 that is) value, so I would suspect something is intercepting the signal on your iOS device.

**Comment by roysG** [comment]
Yes, i get this numbers again and again, even i speak close to phone or tapping

**Comment by roysG** [comment]
You are right!
